// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TextGame.Infrastructure.Database;

#nullable disable

namespace TextGame.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Enemies.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("DamageBlock")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EnemyType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Enemies", (string)null);

                    b.HasDiscriminator<string>("EnemyType").HasValue("Enemy");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("ChestId")
                        .HasColumnType("integer");

                    b.Property<int?>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCarryable")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChestId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("RoomId");

                    b.ToTable("Items", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.Room", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSearched")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("Rooms", (string)null);

                    b.HasDiscriminator<string>("RoomType").HasValue("Room");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChestplateId")
                        .HasColumnType("integer");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentMimicChestId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentRoomId")
                        .HasColumnType("integer");

                    b.Property<int?>("HelmId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGameStarted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInBattle")
                        .HasColumnType("boolean");

                    b.Property<int>("Keys")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeaponId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChestplateId")
                        .IsUnique();

                    b.HasIndex("CurrentMimicChestId")
                        .IsUnique();

                    b.HasIndex("CurrentRoomId")
                        .IsUnique();

                    b.HasIndex("HelmId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponId")
                        .IsUnique();

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HashedPass")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Enemies.Deadman", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Enemies.Enemy");

                    b.HasDiscriminator().HasValue("Deadman");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Enemies.Ghost", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Enemies.Enemy");

                    b.HasDiscriminator().HasValue("Ghost");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Enemies.Lich", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Enemies.Enemy");

                    b.HasDiscriminator().HasValue("Lich");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Enemies.Mimic", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Enemies.Enemy");

                    b.HasDiscriminator().HasValue("Mimic");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Enemies.Skeletor", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Enemies.Enemy");

                    b.HasDiscriminator().HasValue("Skeletor");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Enemies.SkeletorArcher", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Enemies.Enemy");

                    b.HasDiscriminator().HasValue("SkeletorArcher");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Chestplates.Chestplate", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.Property<int>("DamageBlock")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int?>("Durability")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Chestplate");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Helms.Helm", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.Property<int>("DamageBlock")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int?>("Durability")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Helm");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int?>("Durability")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Heals.Bandage", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.Property<int?>("CurrentHealthBoost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHealthBoost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Bandage");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Heals.PowerPotion", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.Property<int?>("CurrentHealthBoost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHealthBoost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("PowerPotion");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Heals.RandomPotion", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.Property<int?>("CurrentHealthBoost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHealthBoost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("RandomPotion");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Heals.RegenPotion", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.Property<int?>("CurrentHealthBoost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHealthBoost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("RegenPotion");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Other.BagOfCoins", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.HasDiscriminator().HasValue("BagOfCoins");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Other.Chest", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<int?>("MimicId")
                        .HasColumnType("integer");

                    b.HasIndex("MimicId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Chest");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Other.Key", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.HasDiscriminator().HasValue("Key");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Other.Map", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Item");

                    b.HasDiscriminator().HasValue("Map");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.BigRoom", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Rooms.Room");

                    b.HasDiscriminator().HasValue("BigRoom");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.EmptyRoom", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Rooms.Room");

                    b.HasDiscriminator().HasValue("EmptyRoom");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.EndRoom", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Rooms.Room");

                    b.HasDiscriminator().HasValue("EndRoom");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.Shop", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Rooms.Room");

                    b.HasDiscriminator().HasValue("Shop");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.SmallRoom", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Rooms.Room");

                    b.HasDiscriminator().HasValue("SmallRoom");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.StartRoom", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Rooms.Room");

                    b.HasDiscriminator().HasValue("StartRoom");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Chestplates.IronCuirass", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Chestplates.Chestplate");

                    b.HasDiscriminator().HasValue("IronCuirass");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Chestplates.LeatherVest", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Chestplates.Chestplate");

                    b.HasDiscriminator().HasValue("LeatherVest");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Helms.IronHelm", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Helms.Helm");

                    b.HasDiscriminator().HasValue("IronHelm");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Helms.LeatherHelm", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Helms.Helm");

                    b.HasDiscriminator().HasValue("LeatherHelm");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Helms.WoodenBucket", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Helms.Helm");

                    b.HasDiscriminator().HasValue("WoodenBucket");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Fists", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon");

                    b.HasDiscriminator().HasValue("Fists");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Swords.GlassSword", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon");

                    b.HasDiscriminator().HasValue("GlassSword");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Swords.IronSword", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon");

                    b.HasDiscriminator().HasValue("IronSword");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Swords.RustSword", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon");

                    b.HasDiscriminator().HasValue("RustSword");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Swords.SilverSword", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon");

                    b.HasDiscriminator().HasValue("SilverSword");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Wands.MagicWand", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon");

                    b.HasDiscriminator().HasValue("MagicWand");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Wands.RandomWand", b =>
                {
                    b.HasBaseType("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon");

                    b.HasDiscriminator().HasValue("RandomWand");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Enemies.Enemy", b =>
                {
                    b.HasOne("TextGame.Domain.Entities.GameObjects.Rooms.Room", "Room")
                        .WithMany("Enemies")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Item", b =>
                {
                    b.HasOne("TextGame.Domain.Entities.GameObjects.Items.Other.Chest", null)
                        .WithMany("Items")
                        .HasForeignKey("ChestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TextGame.Domain.Entities.GameSession", null)
                        .WithMany("Inventory")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TextGame.Domain.Entities.GameObjects.Rooms.Room", "Room")
                        .WithMany("Items")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.Room", b =>
                {
                    b.HasOne("TextGame.Domain.Entities.GameSession", null)
                        .WithMany("Rooms")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Chestplates.Chestplate", "Chestplate")
                        .WithOne()
                        .HasForeignKey("TextGame.Domain.Entities.GameSession", "ChestplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TextGame.Domain.Entities.GameObjects.Items.Other.Chest", "CurrentMimicChest")
                        .WithOne()
                        .HasForeignKey("TextGame.Domain.Entities.GameSession", "CurrentMimicChestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TextGame.Domain.Entities.GameObjects.Rooms.Room", "CurrentRoom")
                        .WithOne()
                        .HasForeignKey("TextGame.Domain.Entities.GameSession", "CurrentRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TextGame.Domain.Entities.GameObjects.Items.Equipments.Armors.Helms.Helm", "Helm")
                        .WithOne()
                        .HasForeignKey("TextGame.Domain.Entities.GameSession", "HelmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TextGame.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TextGame.Domain.Entities.GameObjects.Items.Equipments.Weapons.Weapon", "Weapon")
                        .WithOne()
                        .HasForeignKey("TextGame.Domain.Entities.GameSession", "WeaponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chestplate");

                    b.Navigation("CurrentMimicChest");

                    b.Navigation("CurrentRoom");

                    b.Navigation("Helm");

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TextGame.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Other.Chest", b =>
                {
                    b.HasOne("TextGame.Domain.Entities.GameObjects.Enemies.Mimic", "Mimic")
                        .WithOne()
                        .HasForeignKey("TextGame.Domain.Entities.GameObjects.Items.Other.Chest", "MimicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Mimic");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Rooms.Room", b =>
                {
                    b.Navigation("Enemies");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TextGame.Domain.Entities.GameObjects.Items.Other.Chest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
